### ISSUE TITLE
Issue in Line Allowance Charge

### ISSUE THREAD

**Issue by chamikadesilva** [difi/vefa-ehf-postaward#126]
Hi,

When we adding allowance changes for EHF Order in line level is ask for a allowance charge reason.
and after including allowance charge reason it gives an error saying 'Invalid Content'. 

Please help to sort this matter..

Thanks in advance.

**Comment by SiwMeckelborg** [comment]
thanks for reporting this, we will send this issue to openPEPPOL.

**Comment by SiwMeckelborg** [comment]
The EHF Order does not support Allowance & Charge on line/line item level, only on document level or price level.
