### ISSUE TITLE
NOGOV-T10-R041 and NOGOV-T14-R041 should trigger fatal

### ISSUE THREAD

**Issue by klakegg** [difi/vefa-ehf-postaward#173]
Rules created based on #133.

From the guide:

> The VAT category must be specified on line level. On the header level both the VAT rate and the category must be specified. In addition the basis for calculating the VAT value, the VAT value itself and the total amount for VAT must be specified on the header level.

**Comment by skriverone** [comment]
Is #173 still a Warning or is it now Fatal? We have not been able to deliver EHF-invoices with more than one item since Nov.15th
