### ISSUE TITLE
Element cac:FinancialInstitutionBranch/cbc:ID mandatory, but no rule to check existance

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-ehf-postaward#181]
The element cbc:ID under cac:FinancialInstitutionBranch is mandatory if cac:FinancialInstitutionBranch exists, but there is no rule returning error if element is missing

Full path to element:
/Invoice/cac:PaymentMeans/cac:PayeeFinancialAccount/cac:FinancialInstitutionBranch/cbc:ID

**Comment by klakegg** [comment]
I close this issue as issue #193 answer this issue.
