### ISSUE TITLE
Guides have problems and are not complete

### ISSUE THREAD

**Issue by Lindhart** [difi/vefa-ehf-postaward#188]
These are the problems I have identified by quickly reading the tendering guide and glancing at the building blocks. These are in no way complete.

Problems:
* The SBDH page contains three resources. The OpenPEPPOL is clearly the one to use as implementation guide – it would be beneficial to note that on the page.
* Where can XSDs for the building blocks be found? This is most likely needed when working with SBDH, REM evidence and the UBLs (I managed to find the UBLs – but that is only because I have prior knowledge so I know to follow the UBL 2.1 link). 
* Where can the schematron files be found? They are listed in the tendering guide, but not as links.
* Generally I would recommend having some “Sources” chapters or a general document where the resources needed/relevant for implementation are located.
* The guides mentions business rules and code lists not present in the guides – but does not provide links to where they can be found.
* The Tendering guide provide almost no information about what to put in the fields in the UBLs. 
* The Tendering guide example for Trdm45 (Trn) has invalid information. The “DocumentTypeCode” element under “TenderDocumentReference” has an invalid value.
* The REM evidence is a crucial part of the Trdm45  (Trn) yet it is not even mentioned in the tendering guide. It simply needs to be documented how the REM relates to the Trdm45 on a business level and how individual fields in the REM is mapped to fields in the Trdm45.
* You have a ESPD page (https://vefa.difi.no/preaward/standard/espd/) . Yet the tendering guide doesn’t refer to this in its own ESPD chapter.
* The Trdm implementation guides (ex. https://test-vefa.difi.no/esens/gefeg/tenderreceipt/1.0/) seems to be more a general UBL/XSD documentation. Simple required implementation details are missing. Notable examples from the TenderReceipt are:
   * The element “TenderDocumentReference” has the following description: “References to the business document that the reported decision applies.”. This sentence does not make sense in the context nor does it in any way explain what this element should contain or what the expected number of elements would be.
   * The element “DocumentTypeCode” is required on the “TenderDocumentReference”, but there is no notion of what values are allowed. I believe this type should always follow a specific list, which is not mentioned and in the context of the Trdm45 (Trn) it should always have a single fixed value.
   * There are a number of places where a “schemeID” attribute is required. I believe that for the context the value will always be fixed – yet there are no mentioning of this fixed value.
* There is no guide on how to read the Trdm implementation guides. Quite a lot of elements refer to a requirement or a rule, but there is no reference to where they can be found.
* After reading the guides I am left with a feeling that I need to find the CEN BII profiles and UBL binding documents (ex. “CWA 17027-119 Profile 54 Tendering” and “CWA 17027-205 UBL binding document - Trdm045 Tender Reception Notification” to implement Trdm045 (Trn)) to be able to do implementation. But this is only because I have prior information and therefore know they hold valuable information that is not present in Difis guides. 

Note that in the above I’ve mostly used/looked at Trdm45 (Trn) as an example and still found numerous problems even through this is likely the easiest and smallest Trdm45 to implement. Based on this I would recommend making a full walkthrough of how to implement each Trdm field by field to ensure the guides are adequate.

**Comment by klakegg** [comment]
This is not related to Post Award.
