### ISSUE TITLE
NOGOV-T10-R027 An endpoint identifier scheme MUST have the value 'NO:ORGNR'. 

### ISSUE THREAD

**Issue by Lalithfl3** [difi/vefa-ehf-postaward#190]
Hi 

I have a Issue from yesterday when i validate the EHF Invoice 2.0 documents .. where the CustomerAccountingParty without having Norwegian Organization Number . These invoices are Only to EPrint  not for EInvoicing . Before sending to Print Provider we use to Validate the documents. Earlier we use schemeID="ZZZ" as for those invoices where we don't have Organization Numbers  but from yesterday we got this error message . How I can correct this. Is there any Tag or value to Use for "schemeID"

Thank you

**Comment by klakegg** [comment]
EHF is to be used only between Norwegian organizations.
