### ISSUE TITLE
The VEFA validator does not report an error regarding BII2-T10-R056 

### ISSUE THREAD

**Issue by pettersan** [difi/vefa-ehf-postaward#191]
The VEFA validator does not report an error for the following numbers in <cac:LegalMonetaryTotal>:

<cbc:LineExtensionAmount currencyID="NOK">6311.52</cbc:LineExtensionAmount>
<cbc:TaxExclusiveAmount currencyID="NOK">6311.52</cbc:TaxExclusiveAmount>
<cbc:TaxInclusiveAmount currencyID="NOK">6311.52</cbc:TaxInclusiveAmount>
<cbc:PrepaidAmount currencyID="NOK">1578.59</cbc:PrepaidAmount>
<cbc:PayableAmount currencyID="NOK">6311.52</cbc:PayableAmount>
Any value in <cbc:PrepaidAmount> is accepted. 
We should expect the error message: BII2-T10-R056 

Please note. This will only happen when all numbers mentioned above are equal.

[201612091011_TIA_BEDRIFT_DEV_990329389_1524472_4619167.zip](https://github.com/difi/vefa-ehf-postaward/files/648500/201612091011_TIA_BEDRIFT_DEV_990329389_1524472_4619167.zip)

**Comment by klakegg** [comment]
Is this due to an error in the VEFA validator source code, or the test defined for BII2-T10-R056?

Will this not happen if LineExtensionAmount and TaxExclusiveAmount is removed?
