### ISSUE TITLE
Validator not supporting profile xx?

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-ehf-postaward#194]
Please make sure this box is checked before submitting your issue - thank you!

- [x] Issue is related to guides or validation part of EHF in post-award.

Your issue here:

It seems the validator at vefa.difi.no/validator is not supporting creditnotes using profile xx. Checked the config file, and cannot see profile xx is supported there

**Comment by klakegg** [comment]
This is fixed earlier.
