### ISSUE TITLE
Feil i summering av avgiftskategori - veileder 2.0.9.

### ISSUE THREAD

**Issue by pettersan** [difi/vefa-ehf-postaward#197]
Feil summering av avgiftskategori

Kapittel 6.4.4 «Innhold i beløpselementer» inneholder to linjer med avgiftskategori «S» (25 %).
Kr. 1108,17 + 570,97 gir kr. 1679,14. Summeringen i tabellen viser imidlertid 1689,72?

**Comment by klakegg** [comment]
(51,304*24*0,9) + (44,7823*15*0,85) - 89,774465 +100,345 = 1689,71126 ≈ 1689,72

Ingen feil i summeringen er funnet.
