### ISSUE TITLE
Validering for å stoppe kreditnota med negative tall

### ISSUE THREAD

**Issue by proynes** [difi/vefa-ehf-postaward#199]
Kreditnota skal vel ikke inneholde negative tall. Fint hvis dette kan tydeliggjøres i veileder og hvis validering kan stoppe kreditnota med negative beløp (linje og sum).

**Comment by christian-andersson** [comment]
Hvordan har du tenkt å kreditere en faktura med negative beløp hvis ikke kreditnotaen og kan ha negative beløp?

**Comment by proynes** [comment]
Jeg er ikke ekspert på dette selv, men hvis du ser på denne lenken ser det ut til at vårt innspill støttes fra flere https://www.linkedin.com/groups/4647203/4647203-6234026667216633860?trk=hb_ntf_COMMENTED_ON_GROUP_DISCUSSION_YOU_CREATED#commentID_6235777233865240576

**Comment by christian-andersson** [comment]
jeg tenkte på rader, ikke på totalsummen.

**Comment by klakegg** [comment]
EHF faktura støtter bruk av negative varelinjer, altså må EHF kreditnota også støtte negative varelinjer.

**Comment by proynes** [comment]
I følge våre fakturaeksperter er det her en stor forskjell på om _varelinjene_ er negative (ok) eller om _summen_ er negativ (ikke ok). Er det mulig å få dette bedre beskrevet/presisert i veileder?

**Comment by klakegg** [comment]
Negativ faktura er tillatt. For å kreditere en negativ faktura må også negativ kreditnota være tillatt.
