### ISSUE TITLE
Validering av MVA-koder og prosentsats

### ISSUE THREAD

**Issue by proynes** [difi/vefa-ehf-postaward#200]
Vi får problemer med innhold i faktura når det inkonsistens mellom MVA-koder og prosentsats (EDIT: I samme dokument). Bør kunne valideres.

**Comment by tyskjohan** [comment]
This is non-trivial because the same code can have different percentages over time.

**Comment by proynes** [comment]
Dette gjelder i ett og samme dokument

**Comment by klakegg** [comment]
Hvordan skal dette håndteres når endringer i MVA-satser skjer på nyttårsaften uten nødvendig varsling til at vi skal kunne håndtere det i vårt release-løp?

**Comment by proynes** [comment]
Da er det ikke så enkelt, nei.. Kjenner ikke til hvordan endringsregimet er for MVA-satser og hvordan dette varsles/evt. ikke varsles.. 

For oss i sykehussektoren er i alle fall MVA et stort og komplekst landskap der vi må håndtere alle varianter, vi driver med kjøp, salg, produksjon og har diverse unntak. Generelt ser vi at MVA blir stadig mer utfordrende og kompliserende innen elektronisk handel.

**Comment by SiwMeckelborg** [comment]
Kan det være et forslag her å endre NONAT-T10-R029 til å sjekke kombinasjon av prosentsats og mva-kategori, ikke bare på kategori?
