### ISSUE TITLE
Floating-point arithmetic bug in slack-function

### ISSUE THREAD

**Issue by eriung** [difi/vefa-ehf-postaward#205]
Please make sure this box is checked before submitting your issue - thank you!

- [x] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:

The slack-function in _NONAT-UBL-T10_ and _NONAT-UBL-T14_ seems to suffers from a floating-point arithmetic bug. 

For example: _`$exp = 240.85`_ and _`$slack = 0.01`_, results in: `$exp + xs:decimal($slack) = 240.85999999999999`.
Which is fine as long as `$value < 240.86`, but when `$value = 240.86` the condition `$exp + xs:decimal($slack) &gt;= $val and $exp - xs:decimal($slack) &lt;= $val` will evaluate to false.

Proposed solution:
rewrite:
`$exp + xs:decimal($slack) &gt;= $val and $exp - xs:decimal($slack) &lt;= $val`
to
`u:twodec($exp + xs:decimal($slack)) &gt;= $val and u:twodec($exp - xs:decimal($slack)) &lt;= $val`

**Comment by klakegg** [comment]
This code returns "240.86":
```
<value-of select="240.85 + xs:decimal(0.01)"/>
````

Tested using Saxon HE 9.7.0-14.
