### ISSUE TITLE
Several URL Links in Implementation Guide is not working

### ISSUE THREAD

**Issue by jmyren** [difi/vefa-ehf-postaward#206]
At least in the Norwegian Implementation Guide, the following links are not working:

Chapter 3.6
samhandlingsavtale 

Chapter 5.7
Finansielle forskudd eller forskuddsfakturering
GBS 13 Forskuddsfakturering
GBS 1 Utstedelse av kreditnota

**Comment by Andreas-T** [comment]
Add to this the link for code lists, Chapter 8, Vedlegg C that is redirected to a page with a single code list 'Environmental and Social Labels'.
The rest of the code lists are not found.
