### ISSUE TITLE
Add description on how to use contractnumber on line level in Order

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-ehf-postaward#219]
Please make sure this box is checked before submitting your issue - thank you!

- [x] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:
Ordering from different contracts is often used in the health sector. Add recommondation in guide to use AdditionalItemProperty for this:

```xml
<cac:AdditionalItemProperty>
                <cbc:Name>CONTRACT</cbc:Name>
                <cbc:Value>123455</cbc:Value>
</cac:AdditionalItemProperty>
```

**Comment by klakegg** [comment]
Contract information on line level is not supported in the Order data model. Adding such a recommondation would essentially add expectations to implementers outside the data model. Any such requirements must be communicated to CEN TC440.
