### ISSUE TITLE
MimeCode for XLSX -"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" is not supported?

### ISSUE THREAD

**Issue by aaron-kumar** [difi/vefa-ehf-postaward#221]
It seems that mime code for embedded XLSX attachment -"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" is not supported in vefa validatior. Is this intended or missing functionality?

**Comment by klakegg** [comment]
duplicate of #42.

**Comment by Kanozujo** [comment]
How and where can we start a constructive discussion on the topic of allowed/recommended attachment types? The use of certain attachmenttypes is not a fixed, always closed subject. It varies over time.
