### ISSUE TITLE
Catch Weight missing in Norwegian EHF Catalogue guide

### ISSUE THREAD

**Issue by klakegg** [difi/vefa-ehf-postaward#224]
Please make sure this box is checked before submitting your issue - thank you!

- [X] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:

Chapter "Catch Weight" is missing in the Norwegian version of EHF Catalogue guide.

**Comment by SiwMeckelborg** [comment]
found in chapter 6.6.1:
https://test-vefa.difi.no/ehf/guide/catalogue/1.0/no/#_mengdevariabel_vare
