### ISSUE TITLE
Order confirmation support for partial delivery on order line

### ISSUE THREAD

**Issue by omchwi** [difi/vefa-ehf-postaward#225]
Please make sure this box is checked before submitting your issue - thank you!

- [x] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:
Our customer wishes to receive information about partial deliveries on order lines in their order confirmations. They have previously used xCBL 3.5, where this was included in the message. Now, with the change to UBL EHF, they can no longer see in their confirmations whether an order line will partially delivered before the delivery end date in the message, which increases the uncertainty and need for additional administration, sometimes even additional sourcing from other suppliers that could have been prevented if they had known that the majority of their delivery would arrive as requested.

Please consider adding support for partial deliveries on order lines in the order confirmation messages in UBL EHF standard, and hopefully as soon as possible, as there are probably quite a few other companies needing the same functionality.

Thank you and Best regards,
Charlotte Widstrand

**Comment by 3150jam** [comment]
Exstention to PEPPOL BIS will be included in EHF.  Please send the request to  rfc@peppol.eu.
