### ISSUE TITLE
Catalogue Identification failed on https://vefa.difi.no/validator/ 

### ISSUE THREAD

**Issue by SumanNarwal** [difi/vefa-ehf-postaward#226]
Hi,
 Catalogue Identification failed on https://vefa.difi.no/validator/  
Validation failed for Catalogue on Vefa validator ( https://vefa.difi.no/validator/ ) with 
<cbc:CustomizationID>urn:www.cenbii.eu:transaction:biitrns019:ver2.0:extended:urn:www.peppol.eu:bis:peppol1a:ver4.0</cbc:CustomizationID>	
	<cbc:ProfileID>urn:www.cenbii.eu:profile:bii03:ver2.0</cbc:ProfileID>

![image](https://user-images.githubusercontent.com/31278911/29616128-0d06163c-882e-11e7-864c-09d3d4897b55.png)

[Catalogue _1.txt](https://github.com/difi/vefa-ehf-postaward/files/1245377/Catalogue._1.txt)

Please resolve this issue. 

Thanks,
Suman

**Comment by monze** [comment]
Hey Suman

Just a comment.
The profile in the document 'urn:www.cenbii.eu:profile:bii03:ver2.0' is used for Order only: 
https://joinup.ec.europa.eu/svn/peppol/PostAward/OrderOnly3A/20160310%20-%20PEPPOL_BIS_3A-401.pdf

If you look at the documentation for Catalogue:
https://joinup.ec.europa.eu/svn/peppol/PostAward/CatalogueOnly1A/20160310%20-PEPPOL_BIS_1a-402.pdf

you notice, that you must use the profile'urn:www.cenbii.eu:profile:bii01:ver2.0' (page 36).


Jacob Mogensen
mySupply
Denmark

**Comment by monze** [comment]
And it is not the first time it has been reported:
https://github.com/difi/vefa-ehf-postaward/issues/178

Jacob Mogensen
mySupply
Denmark
