### ISSUE TITLE
Missing validation rule for post-award?

### ISSUE THREAD

**Issue by knutia** [difi/vefa-ehf-postaward#227]
Please make sure this box is checked before submitting your issue - thank you!

- [ x ] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:

I reasantly recived EHF files from a supplier. The files contain the root nodes <inv:Invoice> and <crn:CreditNote> and not the documended  <Invoice> and <CreditNote>.  When taking this up whit the supplier he refere to that it validates acording to https://vefa.difi.no/validator/ and it dos. Is ther a missing rule her or is it ok to use <inv:Invoice> and <crn:CreditNote> as root nodes?

**Comment by klakegg** [comment]
How is use of namespace prefixes on root elements not according to [the guide](https://vefa.difi.no/ehf/guide/invoice-and-creditnote/2.0/no/) and [the specification for namespaces in XML](https://www.w3.org/TR/xml-names/)?

**Comment by knutia** [comment]
It does not. I just assumed the EHF-standard demanded use of default namespace as all the example files does so. If the EHF-standard alow use of namespace prefixes on root elements, I just have to take note of that and uppdate my program to not assume default namespace when prosessing EHF files.
