### ISSUE TITLE
VEFA Validator throws error when comment in EHF file.

### ISSUE THREAD

**Issue by knutia** [difi/vefa-ehf-postaward#228]
Please make sure this box is checked before submitting your issue - thank you!

- [x] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:

Is use of comment (`<!-- comment -->`) not according to [the guide](https://vefa.difi.no/ehf/guide/invoice-and-creditnote/2.0/no/) and [W3C XML standard](https://www.w3.org/TR/xml/#sec-comments)?

https://vefa.difi.no/validator/ throws this error if you have a comment in the EHF file:

Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: Java heap space

**Comment by klakegg** [comment]
Unable to reproduce.

**Comment by knutia** [comment]
Her is [3 files](https://webfiles.infosynergi.no/s/t70fDkTWj5kBTfc) you can download and reproduce it whit. Invoice 7847179 is two files one whit comment and one without. The weird part is that invoice 4745911 dos have a comment but do not give any error.
