### ISSUE TITLE
New PEPPOL BIS validation artifacts

### ISSUE THREAD

**Issue by klakegg** [difi/vefa-ehf-postaward#229]
Please make sure this box is checked before submitting your issue - thank you!

- [X] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:

Include the updated validation artifacts from PEPPOL BIS in the 2017-11-15 release.

**Comment by juskoljo** [comment]
Just to make sure, will there be XSL files in asice file?
