### ISSUE TITLE
Error due to NONAT-T10-R029 when there are more than one line items

### ISSUE THREAD

**Issue by cdruschk** [difi/vefa-ehf-postaward#231]
Please make sure this box is checked before submitting your issue - thank you!

- [X] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:

Error due to NONAT-T10-R029 when there are more than one line items and the //cac:InvoiceLine/cac:TaxTotal/cac:TaxSubtotal segment is present as well. 

cac:InvoiceLine/cac:TaxTotal/cac:TaxSubtotal is outside the EHF specification for UBL 2.1 invoices, but normally it doesn't create any issues. In the past it only created warnings which have been ignored until now. 

Since the rule now creates errors I wonder if the check in it is actually ok. 

Attached are three files. NONAT-T10-R029_failing.xml is failing with errors due to NONAT-T10-R029. 

NONAT-T10-R029_valid_1.xml is valid after I only comment out the //cac:InvoiceLine/cac:TaxTotal/cac:TaxSubtotal segments. 

NONAT-T10-R029_valid_2.xml is valid after I remove the second line item and leave the invoice with only one item including //cac:InvoiceLine/cac:TaxTotal/cac:TaxSubtotal and with updated totals on document level. 

[NONAT-T10-R029.zip](https://github.com/difi/vefa-ehf-postaward/files/1313976/NONAT-T10-R029.zip)

**Comment by klakegg** [comment]
The NONAT-T10-R029 is correctly checking according to elements part of EHF invoice. Any use of elements outside the standard may trigger such side-effects.

Difi announced the change to validation rules in May, and we received no feedback of this in our review period from August 15th to September 14th.

As the rule is according to the standard, and is performing as expected, I see no reason do change the rule.

**Comment by cdruschk** [comment]
That doesn´t change the fact that the rule is incorrect. It doesn´t serve its purpose. The intention of the rule is to check that the taxable amount in a tax subtotal **on document level** is the sum of all invoice lines and allowances and charges on document level with the same tax category. Instead of using the tax subtotal on document level for this check it uses the taxable amount in a tax subtotal on line level. This is wrong. The NONAT-T10-R029 is **not** checking according to elements part of EHF invoice as /Invoice/InvoiceLine/TaxTotal/TaxSubtotal is outside the EHF specification.
