### ISSUE TITLE
NONAT-UBL-T10.xsl result in 'FOAR0001: Division by zero' exception.

### ISSUE THREAD

**Issue by monze** [difi/vefa-ehf-postaward#244]
Please make sure this box is checked before submitting your issue - thank you!

- [x] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:

This issue has been identified in both EHF Invoice and Creditnote 2.0.11 and
EHF Invoice and Creditnote 2.0.12, so it is not a new issue.

We have received a document, containing this invoice line:
```
  <cac:InvoiceLine>
    <cbc:ID>3</cbc:ID>
    <cbc:InvoicedQuantity unitCode="NAR" unitCodeListID="UNECERec20">0</cbc:InvoicedQuantity>
    <cbc:LineExtensionAmount currencyID="NOK">0</cbc:LineExtensionAmount>
    <cbc:AccountingCost>Regnskap</cbc:AccountingCost>
    <cac:OrderLineReference>
      <cbc:LineID>3</cbc:LineID>
    </cac:OrderLineReference>
    <cac:Item>
      <cbc:Name>EHF fakturaer Mai 2017</cbc:Name>
      <cac:SellersItemIdentification>
        <cbc:ID>Regnskap</cbc:ID>
      </cac:SellersItemIdentification>
      <cac:ClassifiedTaxCategory>
        <cbc:ID schemeID="UNCL5305">S</cbc:ID>
        <cbc:Percent>25</cbc:Percent>
        <cac:TaxScheme>
          <cbc:ID>VAT</cbc:ID>
        </cac:TaxScheme>
      </cac:ClassifiedTaxCategory>
    </cac:Item>
    <cac:Price>
      <cbc:PriceAmount currencyID="NOK">0</cbc:PriceAmount>
      <cbc:BaseQuantity>0</cbc:BaseQuantity>
    </cac:Price>
  </cac:InvoiceLine>
```
Note, that the BaseQuantity is 0.

When that document is validated by the Schematron 'NONAT-UBL-T10.xsl', we get the error:
```
FOAR0001: Division by zero
```
When we use Altova to validate the document, it point to this section as root cause for the error:
```
  ...
  <xsl:template match="cac:InvoiceLine" priority="1005" mode="M8">
    <svrl:fired-rule context="cac:InvoiceLine" xmlns:svrl="http://purl.oclc.org/dsdl/svrl" />
    <xsl:variable name="sumCharge" select="sum(cac:AllowanceCharge[child::cbc:ChargeIndicator='true']/cbc:Amount)" />
    <xsl:variable name="sumAllowance" select="sum(cac:AllowanceCharge[child::cbc:ChargeIndicator='false']/cbc:Amount)" />
    <xsl:variable name="baseQuantity" select="xs:decimal(if (cac:Price/cbc:BaseQuantity) then cac:Price/cbc:BaseQuantity else 1)" />
    <xsl:variable name="pricePerUnit" select="xs:decimal(cac:Price/cbc:PriceAmount) div $baseQuantity" />
    <xsl:variable name="quantity" select="xs:decimal(cbc:InvoicedQuantity)" />
    <xsl:variable name="lineExtensionAmount" select="number(cbc:LineExtensionAmount)" />
    <xsl:variable name="quiet" select="not(cbc:InvoicedQuantity) or not(cac:Price/cbc:PriceAmount)" />
    <!--ASSERT -->
    ...
```
In this section, the 'pricePerUnit' is calculated using the 'baseQuantity', and that value is 0, resulting in the error.

As far as I can tell, the BaseQuantity is not mandatory.
So if it exist and contain 0, it should not fail in the schematron validation.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by klakegg** [comment]
Please explain the use case when BaseQuantity should be set to "0".

**Comment by monze** [comment]
We have received this document in the production enviroment, from one of our norwegian customers, and we tranmit the document to another of our norwegian customers.

The issue is, that the Schematron validation crash, and thereby don't complete the validation.
