### ISSUE TITLE
Consistant Inconsistant in EHF Validation using the new Validation artifacts and v2.0.2 of the vefa-validation library

### ISSUE THREAD

**Issue by christian-andersson** [difi/vefa-ehf-postaward#246]
Please make sure this box is checked before submitting your issue - thank you!

- [X] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:

(Not sure if it is the validation rules itself that is causing this problem or the validation engine)

With the new Validation rules from Difi fr om 2017-11-15 located on https://vefa.difi.no/validator/repo/ we get inconsistent validation depending on which EHF file we are trying to validate first.

I have prepared a package showcasing the problem that I will attach. but I will describe it here also.

I have 3 EHF files that I want to validate, depending on the order I validate these (in the same instance of the validator) I get consistent inconsistense in their success or failure to validate.
IF I run the validation of these three EHF files in all permutations (6 executions) I get the following table of success or fail. (Each execution starts with a new startup of the java executable, but each file in the execution is using the same validator instance, since it is not possible to setup multiple instances)

files/executions | 1,2,3 | 1,3,2 | 2,1,3| 2,3,1| 3,1,2| 3,2,1
----------------|------|------|------|------|-----|------
1.xml | success | success | success | success | failure | failure
2.xml | failure | failure | success | success | failure | failure
3.xml | failure | failure | failure | failure | success | success

now, this is an inconsistency that we cannot understand because this inconsistency is very consistent, ie every time I have run this, I have gotten the very same results.

From the looks of it, it seems that the very first EHF always succeeds and the rest depends on what the previous validation result (in the same execution)

The above results was created on MacOS High Sierra using 
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

and I am also getting the same problem on linux using
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by christian-andersson** [comment]
The test files

[validatortest.zip](https://github.com/difi/vefa-ehf-postaward/files/1481366/validatortest.zip)

**Comment by klakegg** [comment]
We don't like duplication of issues. Is this related to the validation artifacts produced?

**Comment by christian-andersson** [comment]
problem was if vefa-validator
