### ISSUE TITLE
2 or more digits in Amount nodes

### ISSUE THREAD

**Issue by stoivo** [difi/vefa-ehf-postaward#251]
Please make sure this box is checked before submitting your issue - thank you!

- [x] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:
I have seen that there are amount nodes which accept 4 digits while others accept only two. 
Is there a place where I can look this up?

`cac:LegalMonetaryTotal  -> cbc:TaxExclusiveAmount` has to be two or less 
`cac:InvoiceLine  -> cac:Price  -> cac:AllowanceCharge  -> cbc:Amount ` can be more

Would be really great if I could look it up from here.
https://vefa.difi.no/ehf/gefeg/invoice/2.0/gu1.htm?https://vefa.difi.no/ehf/gefeg/invoice/2.0/gu200.htm

**Comment by klakegg** [comment]
This is documented in the implementation guide.

**Comment by stoivo** [comment]
From [this (5.4)](https://test-vefa.difi.no/ehf/guide/invoice-and-creditnote/2.0/en/#_rounding) I assume it should always be 2 decimals and if there is more we can ignore them.
