### ISSUE TITLE
EHF-COMMON-R040 generates warning on valid GLN

### ISSUE THREAD

**Issue by digitalnomade** [difi/vefa-ehf-postaward#254]
Please make sure this box is checked before submitting your issue - thank you!

- [x] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:
The EHF-COMMON-R040 rule gives warning on valid GLN.
I have tested with GLN that are registered in GS1 GLN base

**Comment by klakegg** [comment]
No example of failing GLN is provided - nothing to do related to this issue.

**Comment by aslehjelle** [comment]
This is the case for GLN 7080001113360, this is a valid GLN according to GS1, but validation fails.
