### ISSUE TITLE
EHF Invoice and CreditNote Schematron

### ISSUE THREAD

**Issue by ismail-majid** [difi/vefa-ehf-postaward#255]
Please make sure this box is checked before submitting your issue - thank you!

- [ ] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:   Hi Everyone,
I am currently working on validating EHF invoice and credit note. I have use schematron available at https://github.com/difi/vefa-ehf-postaward/tree/master/rules/ehf-invoice-2.0/sch

but it doesn't seem validating the document. It will be great if some one have the latest schematron for validating the EHF invoice and credit note. The https://vefa.difi.no/validator/ showing errors on validation but the schematron are validating so I am not sure if I am using the correct one's

Thank You.

Best Regards,

Majid

**Comment by klakegg** [comment]
Latest Schematron files may be found in this repository.

**Comment by ismail-majid** [comment]
I have tried the availble schematron available at this repository for EHF Inoivce but its still making the document valid.  Can I share the document?

https://github.com/difi/vefa-ehf-postaward/tree/master/rules/ehf-invoice-2.0/sch
