### ISSUE TITLE
XSLT 1.0 Complaint Schematron needed 

### ISSUE THREAD

**Issue by ismail-majid** [difi/vefa-ehf-postaward#258]
Please make sure this box is checked before submitting your issue - thank you!

- [ ] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here: Hi 
I need a Schematron complaint to XSLT 1.0. The current available at https://github.com/difi/vefa-ehf-postaward/tree/master/rules/ehf-invoice-2.0/sch is XSLT 2.0 complaint.

Thank You

Best Regards,

Majid

**Comment by klakegg** [comment]
The files are ISO Schematron with XSLT 2 compliant. XSLT 2 is required according to OpenPEPPOL.
