### ISSUE TITLE
Java validation with ph-schematron

### ISSUE THREAD

**Issue by d142796** [difi/vefa-ehf-postaward#281]
Please make sure this box is checked before submitting your issue - thank you!

- [x] Issue is related to guides or validation part of EHF in post-award.

Issues related to PEPPOL BIS or rules part of PEPPOL BIS must be sent to rfc@peppol.eu.

Your issue here:

Using the following Java/Kotlin kode to verify PEPPOL dokument output invalid schematron file:

**File**: `OPENPEPPOL-UBL-T10.sch`

File is valid in pure implementation only. **_Some are not_**

Link to lib: http://phax.github.io/ph-schematron/

` @Throws(Exception::class)
    fun erValid(@Nonnull aSchematronFile: File, @Nonnull aXMLFile: File): Boolean {
        val aResSCH: SchematronResourceXSLT = SchematronResourceXSLT.fromFile(aSchematronFile)
        require(aResSCH.isValidSchematron) { "Invalid Schematron!" }
        return aResSCH.getSchematronValidity(StreamSource(aXMLFile)).isValid()
    }
`

**Comment by klakegg** [comment]
Could you please provide an example of what is wrong in the files in this repository?

**Comment by d142796** [comment]
Hi @klakegg, please close the issue, the file used was invalid Schematron :)
