### ISSUE TITLE
A VAT number MUST be nine numbers followed by the letters MVA

### ISSUE THREAD

**Issue by anti** [difi/vefa-ehf-postaward#36]
`[NOGOV-T10-R030]- A VAT number MUST be nine numbers followed by the letters MVA`

Is this too strict as some companies are not tax registered and should the PartyTaxScheme be skipped in those cases? Or when there's an incomplete VAT number eg. converting from some other format to EHF 2.03, should we just add the MVA at the end in order to pass the validation?

**Comment by Lamisi** [comment]
When PartyTaxScheme is omitted, this rule is broken [BII2-T10-R044]-A seller VAT identifier MUST be provided if the invoice has a VAT total amount. How do you bypass this?
