### ISSUE TITLE
Element for buyer in addition to AccountingCustomerParty

### ISSUE THREAD

**Issue by pjbridge** [difi/vefa-ehf-postaward#39]
We have seen a need for information about the buyer in addition to the payer in the case where those two are not the same. EHF is starting to be used by utility companies (grid and power suppliers) for re-invoicing, and there is a need for having information about the end user (buyer) in addition to the power supplier which is the accounting customer party. The UBL 2.1 spec,which as I understand EHF is a subset of, includes a buyer element (cac:BuyerCustomerParty). The request is to include this element in a future version of EHF.

**Comment by SiwMeckelborg** [comment]
We will discuss this for a future version of EHF. Adding a new element (even if optional), requires a new version, not just a revision.

**Comment by klakegg** [comment]
An addition buyer element is not part of the European Norm. We are not in a position to add such functionality.
