### ISSUE TITLE
Add SalesOrderID to the Invoice/credit note

### ISSUE THREAD

**Issue by SiwMeckelborg** [difi/vefa-ehf-postaward#43]
Text from LinkedIn "SalesOrderID er leverandørens egen ordrereferanse (og ikke kundens ordrereferanse) og vi har kunder som ønsker dette feltet med på fakturaen"

**Comment by SiwMeckelborg** [comment]
This is new functionality, and cannot be changed in a revision. Added to milestone 2.1.0

**Comment by senikk** [comment]
Anything happended with this one? It goes trough validation (https://vefa.difi.no/validator/) without any error but its still not in the EHF 2.0.12 documentation.

**Comment by klakegg** [comment]
SalesOrderID is part of PEPPOL BIS 3.0. EHF Invoice and Credit Note 2.0 will not receive this update.
